/**
 * 140+ harmful / high-caution cosmetic & consumer-product related substances for seeding.
 * Names are common INCI / trade / class labels users may paste in ingredient lists.
 */
module.exports = [
    'Methylparaben', 'Propylparaben', 'Butylparaben', 'Ethylparaben', 'Isobutylparaben', 'Phenoxyethanol',
    'Formaldehyde', 'Formalin', 'DMDM Hydantoin', 'Imidazolidinyl Urea', 'Diazolidinyl Urea', 'Quaternium-15',
    'Sodium Lauryl Sulfate', 'Sodium Laureth Sulfate', 'Ammonium Lauryl Sulfate', 'Sodium Myreth Sulfate',
    'DEA-Cetyl Phosphate', 'TEA-Lauryl Sulfate', 'Cocamide DEA', 'Lauramide DEA', 'MEA-Borate',
    'Propylene Glycol', 'Mineral Oil', 'Petrolatum', 'Paraffinum Liquidum', 'Liquid Paraffin',
    'BHA', 'BHT', 'Butylated Hydroxyanisole', 'Butylated Hydroxytoluene', 'Hydroquinone',
    'Mercury', 'Thimerosal', 'Lead Acetate', 'Triclosan', 'Triclocarban',
    'DEP', 'DBP', 'DEHP', 'Dibutyl Phthalate', 'Diethyl Phthalate',
    'Synthetic Fragrance', 'Parfum', 'Fragrance', 'Benzophenone-3', 'Oxybenzone',
    'Octinoxate', 'Homosalate', 'Octisalate', 'Avobenzone', 'Retinyl Palmitate',
    'Resorcinol', 'Toluene', 'Xylene', 'Benzene', 'Acetone',
    'Ethanolamine', 'Ammonia', 'Hydrogen Peroxide', 'Aluminum Chlorohydrate', 'Aluminum Zirconium',
    'Coal Tar', 'Coal Tar Solution', 'p-Phenylenediamine', 'PPD', 'Toluene-2,5-diamine',
    'Talc', 'Silica', 'Crystalline Silica', 'Carbon Black', 'Acrylamide',
    '1,4-Dioxane', 'Ethylene Oxide', 'Polyethylene Glycol', 'PEG-8', 'PEG-40',
    'PEG-100 Stearate', 'Polysorbate-20', 'Polysorbate-80', 'Sodium Lauryl Ether Sulfate', 'SLES',
    'Methylisothiazolinone', 'Methylchloroisothiazolinone', 'MIT', 'CMIT', 'Bronopol',
    'Sodium Hydroxymethylglycinate', 'Bronidox', '2-Bromo-2-Nitropropane-1,3-Diol', 'Methenamine', 'Hexamethylenetetramine',
    'EDTA', 'Tetrasodium EDTA', 'Disodium EDTA', 'Calcium Disodium EDTA', 'Etidronic Acid',
    'Styrene', 'Styrene/Acrylates Copolymer', 'Acrylates Copolymer', 'Carbomer', 'Acrylamide/Sodium Acryloyldimethyl Taurate Copolymer',
    'Phenol', 'Cresol', 'Hydroquinone Monomethyl Ether', 'Arbutin synthetic concern', 'Kojic Acid',
    'Nitrosamines', 'Sodium Nitrite cosmetic concern', 'Benzyl Alcohol', 'Benzoic Acid high level', 'Sorbic Acid',
    'FD&C Red No. 40', 'FD&C Yellow No. 5', 'FD&C Blue No. 1', 'Tartrazine', 'Allura Red',
    'Aluminum Starch Octenylsuccinate', 'Alum', 'Potassium Alum', 'Ammonium Alum', 'Zirconium',
    'Retinol', 'Tretinoin', 'Adapalene', 'Salicylic Acid', 'Glycolic Acid',
    'Lactic Acid high concentration', 'Mandelic Acid', 'Citric Acid irritant high', 'Vitamin C Ascorbic Acid low pH',
    'Benzoyl Peroxide', 'Sulfur', 'Resorcinol Monoacetate', 'Alpha Hydroxy Acid', 'Beta Hydroxy Acid',
    'Limonene', 'Linalool', 'Citronellol', 'Geraniol', 'Eugenol',
    'Cinnamal', 'Cinnamyl Alcohol', 'Coumarin', 'Farnesol', 'Amyl Cinnamal',
    'Hexyl Cinnamal', 'Butylphenyl Methylpropional', 'Lyral', 'Hydroxyisohexyl 3-Cyclohexene Carboxaldehyde', 'Oakmoss',
    'Evernia Prunastri', 'Evernia Furfuracea', 'Musk Xylene', 'Musk Ketone', 'Galaxolide',
    'Tonalide', 'Phantolide', 'Cashmeran', 'Vertofix', 'Iso E Super',
    'Nanoparticle Titanium Dioxide', 'Zinc Oxide nano concern', 'Siloxanes D4', 'Cyclotetrasiloxane', 'D5 Cyclopentasiloxane',
    'D6 Cyclohexasiloxane', 'Dimethicone Copolyol', 'Trimethylsiloxysilicate', 'Octamethylcyclotetrasiloxane', 'Decamethylcyclopentasiloxane',
    'Perfluorooctanoic Acid', 'PFOA', 'PFOS', 'Polyfluoroalkyl Substances', 'PTFE',
    'Tremolite', 'Titanium Dioxide', 'Zinc Pyrithione', 'Selenium Sulfide', 'Coal Gas',
    'Hydrofluoric Acid', 'Sodium Fluoride', 'Chlorphenesin', 'Isopropylparaben', 'Ethylparaben Sodium',
    'Sodium Methylparaben', 'Sodium Propylparaben', 'Potassium Sorbate high', 'Sodium Benzoate with ascorbic acid concern',
    'Sodium Lauryl Sulfoacetate', 'Sodium Coco-Sulfate', 'Ammonium Laureth Sulfate', 'Myreth Sulfate', 'Oleth-10 Phosphate'
];
